spring.application.name=spig-backend

# H2 Baza podataka konfiguracija
spring.datasource.url=jdbc:h2:mem:spigdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Omoguci H2 konzolu
spring.h2.console.enabled=true

# Hibernate
spring.jpa.hibernate.ddl-auto=create-drop

# Inicijalizacija baze podataka
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
